name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Build application
        run: >-
          xcodebuild
          -scheme Stats
          -destination 'platform=macOS'
          -configuration Release
          -archivePath build/Stats.xcarchive
          archive
          CODE_SIGNING_ALLOWED=NO
      - name: Package application
        run: >-
          ditto -c -k --keepParent
          build/Stats.xcarchive/Products/Applications/Stats.app
          build/Stats.app.zip
      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: Stats-macOS
          path: build/Stats.app.zip
          if-no-files-found: error
